#!/bin/bash
echo ${PWD}
#DATE=$(curl http://courseroad.mit.edu/output.php?date)
DATE=$(date +"%d-%b-%Y" --date="1 days ago")
env LD_LIBRARY_PATH=~/Downloads/instantclient_11_2 TWO_TASK=warehouse rlwrap -H /tmp/sqlplus_hist ~/Downloads/instantclient_11_2/sqlplus -M "HTML ON" -S dannybd/ohlookawarehousepassword <<EOF
set echo on verify off feedback off 
set linesize 10000
set pagesize 0
spool ../web_scripts/courseroad/output.html
SELECT * FROM cis_course_catalog WHERE last_activity_date>'${DATE}';
spool off;
exit;
EOF
curl -s http://courseroad.mit.edu/output.php?magnets